export enum CommandTypes {
    empty = 'rpn empty',
    q = 'q',
    quit = 'rpn quit',
    h = 'rpn h',
    help = 'rpn help',
    c = 'rpn c',
    clear = 'rpn clear',
    cc = 'rpn cc',
    clearConsole = 'rpn clearconsole',
    cl = 'rpn cl',
    clearAll = 'rpn clearall',
    a = '+',
    add = 'rpn add',
    s = '-',
    subtract = 'rpn subtract',
    m = '*',
    multiply = 'rpn multiply',
}