export enum CommandTypes {
    empty = 'empty',
    q = 'q',
    quit = 'quit',
    h = 'h',
    help = 'help',
    c = 'c',
    clear = 'clear',
    cc = 'cc',
    clearConsole = 'clearconsole',
    cl = 'cl',
    clearAll = 'clearall',
    a = '+',
    add = 'add',
    s = '-',
    subtract = 'subtract',
    m = '*',
    multiply = 'multiply',
    d = '/',
    divide = 'divide',
}